### ISSUE TITLE
Notify: Export kind constants

### ISSUE THREAD

**Issue by ao-david** [ausocean/cloud#117]
Currently, it is up to the caller entirely what the kind in the notify.send method is. It may be beneficial to supply some standard kinds, to ensure that similar kinds are being properly grouped and filtered after consecutive attempts.

**Comment by scruzin** [comment]
I propose that we define and export a `notify.Kind type`, but leave it up to clients to use whatever kinds they want.

**Comment by scruzin** [comment]
`notify.Kind` has been implemented in Pull Request #186.

Notification clients should declare kinds as they fit.
