### ISSUE TITLE
bench: change permission level/add new level for broadcast page access

### ISSUE THREAD

**Issue by saxon-milton** [ausocean/cloud#135]
We're going to need to allow schools/partners to configure broadcasts (they'll need to generate their own auth tokens), but currently admin permissions is required for this. We'll need to either change required permissions, or add a new level which they can use.

**Comment by scruzin** [comment]
The plan is to only allow Premium customers to configure broadcasts and to grant them the necessary admin privileges.
Broadcasts for schools will continue to be managed by AusOcean.

This will be more intuitive once the Broadcast page is relocated under the Admin UI, per Issue #126

**Comment by scruzin** [comment]
We've agreed that the admin privilege is sufficient for broadcast configuration.
