### ISSUE TITLE
datablue: Notify ops of requests from unknown devices

### ISSUE THREAD

**Issue by scruzin** [ausocean/cloud#140]
At present, requests from unknown devices, i.e, devices for which there is no Device entity in the datastore, are silently logged.

It is proposed to notify ops with a new "Device notification" email. Operators may then decide what action to take, including:

- Doing nothing.
- Creating a Device entity and disabling the device.
- Creating a Device entity and enabling the device.

**Comment by ao-david** [comment]
@scruzin was this implemented in #221?

**Comment by scruzin** [comment]
Implemented in #221.
