### ISSUE TITLE
broadcast: OceanBroadcastManager.SaveBroadcast should use transaction

### ISSUE THREAD

**Issue by saxon-milton** [ausocean/cloud#177]
Every other update of the broadcast config uses a transaction so that we can ensure things are synchronised properly, we should also do this with SaveBroadcast from the OceanBroadcastManager

**Comment by scruzin** [comment]
I think we should consider making the BroadcastConfig a database entity, so we have greater flexibility in how we update and access data.

**Comment by saxon-milton** [comment]
> I think we should consider making the BroadcastConfig a database entity, so we have greater flexibility in how we update and access data. That said, the latter would be a big change with the potential to break things, so not a high priority.

I'm open to that, but I'm still not sure how much benefit that would bring at this stage. We only ever reference broadcasts by their name. Is there some other benefit I'm missing ?

**Comment by scruzin** [comment]
In future, we may wish to search for broadcasts by other properties, such as their YouTube account.

**Comment by saxon-milton** [comment]
> In future, we may wish to search for broadcasts by other properties, such as their YouTube account.

True!
