### ISSUE TITLE
broadcast: send notifies also to account broadcast is associated with

### ISSUE THREAD

**Issue by saxon-milton** [ausocean/cloud#185]

**Comment by scruzin** [comment]
I agree this is a desirable feature, but not sure if it is a P1. 

That said, it can be implemented with the `notify.WithRecipients` option, and is probably not too much work.

**Comment by saxon-milton** [comment]
Maybe not P1; I had users like RecFish in mind; they're almost blind to any issues their hardware might have.

**Comment by scruzin** [comment]
PTAL at Issue #189

**Comment by saxon-milton** [comment]
> PTAL at Issue #189

Nice, that should work

**Comment by scruzin** [comment]
This is implemented in Pull Request #234
