### ISSUE TITLE
bench: Saving a cron the navigating to another site saves the cron there too

### ISSUE THREAD

**Issue by trekhopton** [ausocean/cloud#214]
If you save a cron then change site, bench saves the cron at the newly selected site too. This is highly undesirable and could case lots of issues if the user isn't aware of this.

I think this is because the site menu reloads the page but because the cron page submits a form on reload, the new cron form is submitted to the new site as soon as it loads.

**Comment by ao-david** [comment]
I think at some point we need to decide on a standard for how forms should be submitted, and make sure that all of our pages follow this standard so that we don't keep running into these issues.

To solve this issue, we can probably use custom-handling of the site-change event I think. #90

**Comment by scruzin** [comment]
This behavior is a regression, as the `/set/crons/edit` form method was only invoked manually previously.

Changes to site menu handling since the cron page was originally implemented is most likely the cause.

@ao-david suggestion sounds like the way to go.

**Comment by scruzin** [comment]
Another, simpler solution is to make sure we always return to the `/set/crons` URL after any form submission, not `/set/crowns/edit`.

**Comment by scruzin** [comment]
As a rule, if there is a simple workaround then a bug is not a P1. The workaround here is to simply re-invoke the cron page from the main before changing sites.
