### ISSUE TITLE
Bench: Moving a device breaks variables and actuators

### ISSUE THREAD

**Issue by ao-david** [ausocean/cloud#288]
When using /utilities to move a device, variables are not carried across to the new site. Additionally, actuators do not properly move either, resulting in issues with ```processActuators``` hence resulting in the status not showing correctly. As the uptime variable is updated _after_ responding to the client

**Comment by scruzin** [comment]
Variables, actuators and sensors do not need to be "moved" per se, because they're automatically linked to a device via the device's MAC address, not the device's name. This has been the behavior ever since SensorV2 and ActuatorV2 were introduced.

If device variables, actuators and/or sensors are not showing after a device has moved, it is most likely because the device's MAC address has been inadvertently changed (a no-no).

**Comment by ao-david** [comment]
Variables are still generally gotten and set primarily by the skey, and so getting the vars for a device will filter by the skey first, before filtering by the mac.

As it turns out, the issue is caused yet again by form resubmission. 

If you are on site 1, and move a device to site 2, then on the utils page select site 2 in the site menu, the form resubmits, and seems to delete the var.

**Comment by scruzin** [comment]
Okay, variables that are moved should be "re-keyed" to the new site. This used to be the case (but perhaps I'm thinking of NetReceiver).

Nothing is required for sensors and actuators though, as they don't reference the site.

To get sensors and actuators for a site, effectively entails getting the devices for the site and then finding the sensors actuators for each device (for said site).

**Comment by scruzin** [comment]
Variables _are_ getting re-keyed. See line 532 in admin.go

**Comment by ao-david** [comment]
> Variables _are_ getting re-keyed. See line 532 in admin.go

Yes, this works, but for some reason, changing the site on the utilities page resubmits the form. Since this means that the variable is being put back onto the same site, when you put, then delete the variable it just ends up deleting the var.
```
err := model.PutVariable(ctx, settingsStore, targetSkey, v.Name, v.Value)
if err != nil {
	return fmt.Errorf("cannot put variable %d.%s: %v", targetSkey, v.Name, err)
}
err = model.DeleteVariable(ctx, settingsStore, skey, v.Name)
if err != nil {
	return fmt.Errorf("cannot delete variable %d.%s: %v", skey, v.Name, err)
}
```
consider the above if targetSkey and skey are the same...

**Comment by ao-david** [comment]
Specifically regarding controllers, there seem to be an issue finding the variables that correspond to the actuators. After moving a device, it seems that they still report okay, but if I copy the poll request to datablue and make the request, I get the following error
```"failed to get actuator by 44179313ef7f.X14: datastore: no such entity"```
however, the variable that it is looking for is actually 74868042493823.X14 (which does exist), I'm under the impression that vars are named with the decimal value of the mac address?

**Comment by scruzin** [comment]
> > Variables _are_ getting re-keyed. See line 532 in admin.go
> 
> Yes, this works, but for some reason, changing the site on the utilities page resubmits the form. Since this means that the variable is being put back onto the same site, when you put, then delete the variable it just ends up deleting the var.
> 
> ```
> err := model.PutVariable(ctx, settingsStore, targetSkey, v.Name, v.Value)
> if err != nil {
> 	return fmt.Errorf("cannot put variable %d.%s: %v", targetSkey, v.Name, err)
> }
> err = model.DeleteVariable(ctx, settingsStore, skey, v.Name)
> if err != nil {
> 	return fmt.Errorf("cannot delete variable %d.%s: %v", skey, v.Name, err)
> }
> ```
> 
> consider the above if targetSkey and skey are the same...

As you say, the root cause is the duplicate form submission. 

We can add a check though to defend against identical targetSkey and skey.

**Comment by scruzin** [comment]
> Specifically regarding controllers, there seem to be an issue finding the variables that correspond to the actuators. After moving a device, it seems that they still report okay, but if I copy the poll request to datablue and make the request, I get the following error `"failed to get actuator by 44179313ef7f.X14: datastore: no such entity"` however, the variable that it is looking for is actually 74868042493823.X14 (which does exist), I'm under the impression that vars are named with the decimal value of the mac address?

Vars for a device should be scoped to the MAC address (string), not the encoded MAC address (integer).
So `44179313ef7f.X14` is the correct form.

**Comment by davidsutts** [comment]
I realised that the error message was actually printing a combo of the actuator scope, and the variable. See #289

**Comment by scruzin** [comment]
Actually, I misread your earlier comment.

- Variables use the MAC address (string). The latter is the `scope` which permits all vars for a given device to be easily retrieved.
- Actuators and sensors use the encoded MAC address (integer).
