### ISSUE TITLE
Center: update pkg to use run_pi_client.sh v2.0.0

### ISSUE THREAD

**Issue by ao-david** [ausocean/cloud#291]
Currently hydrophone package uses run_pi_client.sh v1.0.0 which is not compatible with the current version of the ausocean.service. This means that when the pg gets upgraded, this script gets reverted to an older version which is then not run properly by the service.

**Comment by scruzin** [comment]
Now that run_pi_client.sh is part of the image, it can be removed from the package.
We can always re-add it to a future version of the package if necessary.
