### ISSUE TITLE
TV: Defaulting to global notifier has issues

### ISSUE THREAD

**Issue by ao-david** [ausocean/cloud#297]
On the myponga site, looking at the tv logs, there seems to be some issues regarding defaulting to the global notifier.

```
broadcast context notifier is nil, setting to global notifier
(name: RecFish SA Cod-Cam Myponga 1 (east), id: iiC_duHM7kA) could not send health notification: could not send mail: could not send mail: {"Messages":[{"Errors":[{"ErrorClass":"","ErrorMessage":"You must provide at least one item in the collection.","ErrorRelatedTo":["To"],"StatusCode":400}]}]}
```

It seems like it may be caused by a issue when looking up the recipients, and not finding any. We maybe should default to at least sending an email to ops@ausocean.

**Comment by scruzin** [comment]
I don't think we should provide a default for Ops Email. If it's not defined, then no email should be sent.

Of course, we should ensure it is defined for all customer sites.

I only have access to one Myponga site (namely #1345054408) which _does_ define values for Ops Email and YouTube Email, although the former is ops@ and should be premium-ops@.

Presumably, this bug refers to the second Myponga site. If so, ensure that Ops Email and YouTube Email are correctly set.

**Comment by ao-david** [comment]
There is only one myponga site, which does have the ops email, so I think the bug is a lower level

**Comment by scruzin** [comment]
From a quick glance at the code, it looks like the notifiers are being instantiated correctly (at least initially). 

Specifically, it is the `WithRecipientLookup` option that specifies which recipients to use:

`notify.WithRecipientLookup(tvRecipients)`

**Comment by scruzin** [comment]
I recommend adding some logging to line 232 of oceantv/main.go, to log when `site.OpsEmail` is empty. `site.YouTubeEmail` may be empty, though.

**Comment by scruzin** [comment]
The bug is indeed inside notify.Send. I believe it is a regression caused by the refactoring send() out of Send().
