### ISSUE TITLE
Stream Content Access for Specific YouTube Membership Tier via API

### ISSUE THREAD

**Issue by catherinelarkin** [ausocean/cloud#314]
We need to implement a feature that allows us to send live stream content on YouTube to a specific membership tier, particularly the $3.99/month "Premium Tier" for AusOcean underwater streams. The feature should utilise YouTube's Live Streaming API and Memberships API to restrict access based on the user's subscription level.

**Comment by ao-david** [comment]
As discussed, I am not sure that this is possible using the API. Instead, we will aim to rely on permanent streams that can be moved to members only manually once.
