### ISSUE TITLE
tv: move hardwareRestarting state to broadcast machine

### ISSUE THREAD

**Issue by trekhopton** [ausocean/cloud#341]
hardwareResetRequestEvent is triggered when the directLiveUnhealthy and vidforwardPermanentLiveUnhealthy states need to powercycle the hardware.
I propose this event is handled by the broadcast machine, not the hardware machine because the actual hardware has no concept of a reset. The hardware machine should reflect the actual hardware state, which is usually either off or on, and the broadcast machine should manage that via requests, remembering if a camera needs to be powered on again after it is powered off or not.

This will simplify the hardware machine's state transitions.

**Comment by saxon-milton** [comment]
I'm not sure I necessarily agree with this. I don't think it matters that the actual hardware doesn't has a concept of a reset. The hardware state machine is on a abstraction level above the actual hardware, so there's no reason why it can't have a concept of a reset. In the same way that hardware for a computer doesn't have a concept of reset, the OS/BIOS orchestrates that.

**Comment by trekhopton** [comment]
This is no longer how we're going to process hardwareResetRequestEvents. The hardware state machine will have a concept of a restart.
