### ISSUE TITLE
broadcast: reuse the same broadcast object when there's a failure.

### ISSUE THREAD

**Issue by saxon-milton** [ausocean/cloud#42]
Currently when a broadcast fails, another one is created; for various failure reasons, this can happen multiple times, and to the YouTube subscribers, it appears as different streams in their feed. This is undesirable and we should figure out how to reuse the same broadcast to retry. Or at the very least delete the old one programmatically so that two don’t exist at the same time.

**Comment by ao-david** [comment]
Given that the config is now stateful (from my understanding), we should just be able to reuse the existing broadcast ID, RTMP url etc if the last time that it was update was the current day. 

We should still be careful and make sure that we can still request a create a new stream if there is actually an issue with the youtube end of things at some point.

in broadcast_manager.go:

when we call svc.CreateBroadcast() we should see if there is a id and RTMPurl associated with the config already (current day) and then make a decision from there.

**Comment by scruzin** [comment]
Is it affecting currently broadcasts? If so, I agree it is a P0.
If it has a workaround, then P2 is okay. 
If not, let's bump to P1.

**Comment by saxon-milton** [comment]
This is generally not a P0 but if there is some other issue that causes repeated create requests to YT then the issue is amplified. Perhaps it then warrants P1...
