### ISSUE TITLE
broadcast: stay in slate if hardware failure

### ISSUE THREAD

**Issue by saxon-milton** [ausocean/cloud#54]
If during transition from slate to live we cannot power on the hardware we currently try to do the whole broadcast creation and start process again. This behaviour could be more intelligent. We should instead just stay in the slate state. This is more sensible.

**Comment by scruzin** [comment]
I agree that staying in state mode is sensible, but we should also provide some feedback to the broadcast administrator.

**Comment by saxon-milton** [comment]
Yes, sorry, was meant to also suggest doing an email notify.
