### ISSUE TITLE
bench: Make template directory dynamic

### ISSUE THREAD

**Issue by scruzin** [ausocean/cloud#62]
Resolving Issue #60, required changing the template directory from "t" to "cmd/oceanbench/t".

In standalone mode, however, it is normal to execute ./oceanbench from cmd/oceanbench. Therefore the latter is the working directory, which means the templates are not found.

Therefore the template directory should be dynamic.

**Comment by scruzin** [comment]
Note that running oceanbench from the repo level level permits the template files to be found, but moves the problem to the static files, which cannot be found.

**Comment by scruzin** [comment]
The check needs to be a bit more sophisticated  to detect whenever we're running locally, not just in standalone mode. @trekhopton

**Comment by trekhopton** [comment]
resolved in PR #65
