### ISSUE TITLE
broadcast: only send bad health notification after consecutive issues

### ISSUE THREAD

**Issue by saxon-milton** [ausocean/cloud#78]
We frequently get a situation where there's a temporary health issue like "noData". This is generally just due to a momentary lapse in bandwidth. We therefore don't care all that much unless it continues. So let's only use email notification if we get consecutive problems.

**Comment by scruzin** [comment]
This might also be a good use case for sending an email alert to a dedicated email address, such as broadcast-ops@.
Less serious alerts could continue to use ops@.
